massive uShare code update: discard libupnp, have a complete use of libdlna to create a DMS

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,14 +34,11 @@ show_help(){
   echo "  --localedir=DIR             use locales from DIR [DATADIR/locale]"
   echo ""
   echo "Extended options:"
-  echo "  --enable-dlna               enable DLNA support through libldna"
-  echo "  --disable-dlna              disable DLNA support"
   echo "  --disable-nls               do not use Native Language Support"
   echo "  --enable-fam                enable File Alteration Monitor support"
   echo "  --disable-fam               disable File Alteration Monitor support"
   echo ""
   echo "Search paths:"
-  echo "  --with-libupnp-dir=DIR      check for libupnp installed in DIR"
   echo "  --with-libdlna-dir=DIR      check for libdlna installed in DIR"
   echo ""
   echo "Advanced options (experts only):"
@@ -297,7 +294,6 @@ bindir='${PREFIX}/bin'
 sysconfdir='${PREFIX}/etc'
 datadir='${PREFIX}/share'
 localedir='${datadir}/locale'
-dlna="no"
 fam="no"
 nls="yes"
 cc="gcc"
@@ -417,15 +413,9 @@ for opt do
   ;;
   --localedir=*) localedir="$optval";
   ;;
-  --with-libupnp-dir=*) libupnpdir="$optval";
-  ;;
   --with-libdlna-dir=*) libdlnadir="$optval";
   ;;
   --disable-nls) nls="no"
-  ;;
-  --enable-dlna) dlna="yes"
-  ;;
-  --disable-dlna) dlna="no"
   ;;
   --enable-fam) fam="yes"
   ;;
@@ -639,43 +629,19 @@ echolog "Checking for iconv ..."
 check_lib iconv.h iconv "" && add_cflags -DHAVE_ICONV
 
 #################################################
-#   check for libupnp and friends (mandatory)
+#   check for libdlna (mandatory)
 #################################################
-if [ -n "$libupnpdir" ]; then
-  check_cflags -I$libupnpdir
-  check_ldflags -L$libupnpdir
+libdlna_min_version="0.2.1"
+echolog "Checking for libdlna >= $libdlna_min_version ..."
+if [ -n "$libdlnadir" ]; then
+  check_cflags -I$libdlnadir
+  check_ldflags -L$libdlnadir
 fi
-
-echolog "Checking for libixml ..."
-check_lib upnp/ixml.h ixmlRelaxParser -lixml || die "Error, can't find libixml !"
-
-echolog "Checking for libthreadutil ..."
-check_lib upnp/ThreadPool.h ThreadPoolAdd "-lthreadutil -lpthread" || die "Error, can't find libthreadutil !"
+check_lib dlna.h dlna_register_all_media_profiles -ldlna || die "Error, can't find libdlna (install it) !"
+check_lib_version libdlna $libdlna_min_version || die "Error, libdlna < $libdlna_min_version !"
+add_cflags `pkg-config libdlna --cflags`
+add_extralibs `pkg-config libdlna --libs`
 add_extralibs -lpthread
-
-libupnp_min_version="1.4.2"
-echolog "Checking for libupnp >= $libupnp_min_version ..."
-check_lib upnp/upnp.h UpnpSetMaxContentLength -lupnp || die "Error, can't find libupnp !"
-check_lib_version libupnp $libupnp_min_version || die "Error, libupnp < $libupnp_min_version !"
-add_cflags `pkg-config libupnp --cflags`
-add_extralibs `pkg-config libupnp --libs`
-
-#################################################
-#   check for libdlna (mandatory if enabled)
-#################################################
-if test "$dlna" = "yes"; then
-  libdlna_min_version="0.2.1"
-  echolog "Checking for libdlna >= $libdlna_min_version ..."
-  if [ -n "$libdlnadir" ]; then
-    check_cflags -I$libdlnadir
-    check_ldflags -L$libdlnadir
-  fi
-  check_lib dlna.h dlna_register_all_media_profiles -ldlna || die "Error, can't find libdlna (install it or use --disable-dlna) !"
-  check_lib_version libdlna $libdlna_min_version || die "Error, libdlna < $libdlna_min_version !"
-  add_cflags -DHAVE_DLNA
-  add_cflags `pkg-config libdlna --cflags`
-  add_extralibs `pkg-config libdlna --libs`
-fi
 
 #################################################
 #   check for libfam
@@ -693,15 +659,13 @@ fi
 echolog ""
 echolog "uShare: configure is OK"
 echolog "  version            $VERSION"
-echolog "  using libupnp      `pkg-config libupnp --modversion`"
-test $dlna = yes && echolog "  using libdlna      `pkg-config libdlna --modversion`"
+echolog "  using libdlna      `pkg-config libdlna --modversion`"
 echolog "configuration:"
 echolog "  install prefix     $PREFIX"
 echolog "  configuration dir  $sysconfdir"
 echolog "  data dir           $datadir"
 echolog "  locales dir        $localedir"
 echolog "  NLS support        $nls"
-echolog "  DLNA support       $dlna"
 echolog "  C compiler         $cc"
 echolog "  STRIP              $strip"
 echolog "  make               $make"
